version: '3.8'

volumes:
  prometheus_volume:
  grafana_volume:
#  influxdbv2:
#  postgres_data:
#    external: true

services:
  app:
    build:
      dockerfile: cmd/monolith/Dockerfile
      context: ./
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    networks:
      - big_net

  db:
    image: postgres:15.4-alpine
    container_name: db
    restart: on-failure
    volumes:
      - ./volumes/postgres_data/pgmaster:/var/lib/postgresql/data
      - ./db/migrations/data:/data
    networks:
      - big_net
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h db"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - "5432:${POSTGRES_PORT}"

# TODO
  db_slave1:
    image: postgres:15.4-alpine
    container_name: db_slave1
    restart: unless-stopped
    volumes:
      - ./volumes/postgres_data/pgslave1/pgslave:/var/lib/postgresql/data
      - ./db/migrations/data:/data
    networks:
      - big_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h db"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s

  db_slave2:
    image: postgres:15.4-alpine
    container_name: db_slave2
    restart: unless-stopped
    volumes:
      - ./volumes/postgres_data/pgslave2/pgslave:/var/lib/postgresql/data
      - ./db/migrations/data:/data
    networks:
      - big_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h db"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s

  pg-exporter-master:
    image: prometheuscommunity/postgres-exporter:v0.12.0
    container_name: pg-exporter-db-master
#    env_file:
#      - .env
    environment:
      - DATA_SOURCE_NAME=postgres://postgres:password@db:5432/social_net?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=password
    ports:
      - 9187:9187
    depends_on:
      - db
    networks:
      - big_net

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./build/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_volume:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=10d
      - --web.enable-lifecycle
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter
    depends_on:
      - cadvisor
      - node-exporter
      - pg-exporter-master
    networks:
      - big_net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - big_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: monitoring_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    command:
      - --docker_only=true
    depends_on:
      - db
    networks:
      - big_net

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - grafana_volume:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    networks:
      - big_net
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
#      - GF_USERS_ALLOW_SIGN_UP=false
#      - GF_SERVER_DOMAIN=myrul.com
#      - GF_SMTP_ENABLED=true
#      - GF_SMTP_HOST=smtp.gmail.com:587
#      - GF_SMTP_USER=myadrress@gmail.com
#      - GF_SMTP_PASSWORD=mypassword
#      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com

#  grafana:
#    image: grafana/grafana-enterprise
#    container_name: grafana
#    restart: unless-stopped
#    ports:
#      - '3000:3000'
#
#  influxdb:
#    image: influxdb:2.6-alpine
#    env_file:
#      - influxv2.env
#    volumes:
#      # Mount for influxdb data directory and configuration
#      - influxdbv2:/var/lib/influxdb2:rw
#    ports:
#      - "8086:8086"
#
#  telegraf:
#    image: telegraf:1.25-alpine
#    depends_on:
#      - influxdb
#    volumes:
#      # Mount for telegraf config
#      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf:ro
#    env_file:
#      - influxv2.env

networks:
  big_net:
    driver: bridge